### ISSUE TITLE
Incorrect payer count in sprinters - eg. Players 3/2

### ISSUE THREAD

**Issue by Sigurs** [GazamoGames/Issues#16]
![2015-07-03_2318](https://cloud.githubusercontent.com/assets/10909187/8504440/2fb84c66-21da-11e5-9b97-c544ea7da111.png)

**Comment by mkotb** [comment]
The denominator is the amount of minimum players, are you suggesting to have it increase if the numerator is higher?

**Comment by Sigurs** [comment]
For me it looks like
"3 out of 2 max. players"
Maybe clarify a little?

**Comment by mkotb** [comment]
Having the denominator at the max players is more sensible anyway, will change.

**Comment by mkotb** [comment]
Added, will be previewed in the next update.
