### ISSUE TITLE
Players get kicked from game lobby to hub.

### ISSUE THREAD

**Issue by EddRJ** [GazamoGames/Issues#18]
Game will finish, players get teleported back to the main game lobby, sometimes upon loading in it will either disconnect you entirly or kick you bakc to the main hub.

**Comment by mkotb** [comment]
Are their any variables that could impact whether they get kicked to the hub or not? Are they sent any message?

**Comment by EddRJ** [comment]
No message will get sent, just gets disconneccted or kicked backc to hub. 

You try and load in, sometimes that freezes on you you have to shut your mc down and start back up. 

or just simply frezes and kicks you abkc to hub. This is as much as i can explain it, zero error messages on user end. I have experianced this also.

**Comment by mkotb** [comment]
Have you noticed it commonly within any specific game?

**Comment by EddRJ** [comment]
Sprinters its happened a fe wtime but thats cause i played it more than any other. Boomers its happened on once to me. 

My guess is it woudl be atiming issue speaking to the server and getting info back etc.

**Comment by exception** [comment]
Found out what the problem was, the portal to travel back to the Hub was bigger than it should've been and players were stepping on it and getting warped to the hub. Will be fixed with the next hub update.
