### ISSUE TITLE
AntiCheat Jumpboost still having issues. Sorry.

### ISSUE THREAD

**Issue by EddRJ** [GazamoGames/Issues#19]
Jumpboosts still having issues for players. It is not constant, but it will glitch where they get teelported back for flying or kicked entirly.

**Comment by mkotb** [comment]
that passive aggressive "sorry"

**Comment by EddRJ** [comment]
its not passive agressive, i emant it cause i know its really annoying. YOU BASTARD!, oh wait thats just agressive nvm.
