### ISSUE TITLE
Boomers Missing Feature

### ISSUE THREAD

**Issue by EddRJ** [GazamoGames/Issues#21]
![](https://i.imgur.com/KutRCvu.jpg)

On each pedastal should be a person holding one of the 5 weps in boomers. This is just to show the kits off, looks dope and gets people excited. 

Thanks :)

**Comment by mkotb** [comment]
edit: embedded image and used imgur

**Comment by exception** [comment]
Would be cool if when you clicked them it would buy the kit

**Comment by EddRJ** [comment]
yes that would be very cool.

**Comment by EddRJ** [comment]
Have ahologram on each of them:

Name of Kit
     Price
Ciick To Buy

**Comment by mkotb** [comment]
Feature added

![](http://i.imgur.com/VymDvtc.gif)

**Comment by exception** [comment]
@mkotb Screenshot kinda broken
