### ISSUE TITLE
Coins Still not updating after game ends

### ISSUE THREAD

**Issue by EddRJ** [GazamoGames/Issues#22]
Can't really think of any other way to describe this one.

**Comment by mkotb** [comment]
What happens exactly? Walk me through it.

**Comment by EddRJ** [comment]
for example: 

Win game of sprinters, get back to the waiting room where it gives you teh coins says how much you won. Get teleported back to game lobby, it has not updated from the previous amount. But if i relog, its then updated.

**Comment by mkotb** [comment]
I recall this to be a bug to be fixed before and I am not able to replicate it currently, could you get some form of proof from this bug?

**Comment by EddRJ** [comment]
PLEASE IGNORE ME IM INSANE. Was looking at woorng thing. It works.
