### ISSUE TITLE
Sprinters: [Map=Desert] Barrier blocks

### ISSUE THREAD

**Issue by NeroHornley** [GazamoGames/Issues#28]
At the first jump there is a row of barrier blocks that players keep hitting because they cant see them and dont know they exist. As of that alot of players are frustrated that they lose because of that.
The row that im standing infront of in the screenshot. (if more screenshots need to be given just ask :))
![2015-07-27_20 45 29](https://cloud.githubusercontent.com/assets/13056845/8938920/bd24862e-3561-11e5-9f6e-d484c7a7a534.png)

**Comment by exception** [comment]
Will be reported to the Build Team to fix, thanks for reporting.
