### ISSUE TITLE
The "you're a wizard Harry" toy from the token shop doesn't work properly

### ISSUE THREAD

**Issue by Jossieboymetsnor** [GazamoGames/Issues#4]
The item "you're a wizard Harry" doesn't seem to be changing players into pigs for 5 seconds, but rather, making them invisible to the player using it, and then making the player who has been changed into a pig (well... turned invisible) crash.

**Comment by exception** [comment]
@mkotb This is a Disguising bug, we'll look into it soon.

**Comment by exception** [comment]
For now this seems not fixable as we need to rethink the way of disguising palyers.

**Comment by exception** [comment]
Toy will not continue to be developed until a new disguising system is developed. Closing issue until further notice.
