### ISSUE TITLE
You can get stuck on futuristic sprinters map (build)

### ISSUE THREAD

**Issue by NeroHornley** [GazamoGames/Issues#7]
At some places you can jump into parts of a building and you can get out.

**Comment by mkotb** [comment]
Please send screenshots of the areas which intended to be rebuild, note that for us to fix any issue we need more information to know where to go and how we can fix it.

**Comment by NeroHornley** [comment]
http://imgur.com/gTALAk8,Q7nqauu,rgP6zZ4#2

**Comment by mkotb** [comment]
You really have to try for that one, will not fix.
