### ISSUE TITLE
Texturepack for boomers failed to send

### ISSUE THREAD

**Issue by NeroHornley** [GazamoGames/Issues#8]
Alot of people are having trouble getting the texturepack.

**Comment by mkotb** [comment]
Are they not prompted with the resource pack message at all or do they click deny?

**Comment by NeroHornley** [comment]
it says for the playere Texturepack could not be send

**Comment by NeroHornley** [comment]
and some press no and cant get the texturepack after that, logging out doesnt work for them either

**Comment by exception** [comment]
@NeroHornley If the players click "No" the MC Client automatically sets all incoming texture packs request to "Denied", meaning that every time we send them a resourcepack it will fail to download as it's going to be denied. This is why we should let know that players that click "No" and actually need the texure pack, need to go back to the multi player screen, edit gazamogames, and set resource packs to enabled or prompt.

**Comment by NeroHornley** [comment]
ah ok thx for letting me know :)
