### ISSUE TITLE
Profanity's are screwed up

### ISSUE THREAD

**Issue by NeroHornley** [GazamoGames/Issues#9]
Saying tim, nero, it and think is apperently a profanity.

**Comment by NeroHornley** [comment]
tip is also blacklisted

**Comment by mkotb** [comment]
Yes, noticed this too. Seems as if the sensitivity of my algorithm is too high.

**Comment by exception** [comment]
@mkotb Status on the fix?

**Comment by mkotb** [comment]
what to heck mazen, what's the status on the fix???
